-- Name: Ragdoll
-- Path: game:GetService("ReplicatedStorage").ACS_Engine.Modules.Ragdoll
-- Class: ModuleScript
-- Exploit: Xeno 
-- Time to decompile: 0.6768076999996993 seconds

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-02-18 07:18:44
-- Luau version 6, Types version 3
-- Time taken: 0.007663 seconds

local Players_upvr = game.Players
return function(arg1) -- Line 4
	--[[ Upvalues[1]:
		[1]: Players_upvr (readonly)
	]]
	if arg1 ~= nil then
		if arg1.Humanoid.RigType == Enum.HumanoidRigType.R6 then
			local Head_2 = arg1:FindFirstChild("Head")
			local Humanoid = arg1:FindFirstChild("Humanoid")
			local Left_Arm = arg1:FindFirstChild("Left Arm")
			local Right_Arm = arg1:FindFirstChild("Right Arm")
			local Torso = arg1:FindFirstChild("Torso")
			Humanoid.PlatformStand = true
			Humanoid.AutoRotate = false
			local Attachment_10 = Instance.new("Attachment")
			Attachment_10.Name = "HeadA"
			Attachment_10.Parent = Head_2
			Attachment_10.Position = Vector3.new(0, -0.5, 0)
			Attachment_10.Rotation = Vector3.new(0, 0, -90)
			Attachment_10.Axis = Vector3.new(0, -1, 0)
			Attachment_10.SecondaryAxis = Vector3.new(1, 0, 0)
			local Attachment = Instance.new("Attachment")
			Attachment.Name = "LeftArmA"
			Attachment.Parent = Left_Arm
			Attachment.Position = Vector3.new(0.5, 0.60000, 0)
			Attachment.Rotation = Vector3.new(0, 0, 0)
			Attachment.Axis = Vector3.new(1, 0, 0)
			Attachment.SecondaryAxis = Vector3.new(0, 1, 0)
			local Attachment_6 = Instance.new("Attachment")
			Attachment_6.Name = "LeftLegA"
			Attachment_6.Parent = arg1:FindFirstChild("Left Leg")
			Attachment_6.Position = Vector3.new(0.10000, 1, -0)
			Attachment_6.Rotation = Vector3.new(-0, -0, -90)
			Attachment_6.Axis = Vector3.new(-0, -1, 0)
			Attachment_6.SecondaryAxis = Vector3.new(1, 0, 0)
			local Attachment_8 = Instance.new("Attachment")
			Attachment_8.Name = "RightArmA"
			Attachment_8.Parent = Right_Arm
			Attachment_8.Position = Vector3.new(-0.5, 0.60000, 0)
			Attachment_8.Rotation = Vector3.new(-180, 0, -180)
			Attachment_8.Axis = Vector3.new(-1, 0, 0)
			Attachment_8.SecondaryAxis = Vector3.new(0, 1, 0)
			local Attachment_4 = Instance.new("Attachment")
			Attachment_4.Name = "RightLegA"
			Attachment_4.Parent = arg1:FindFirstChild("Right Leg")
			Attachment_4.Position = Vector3.new(-0.1000, 1, 0)
			Attachment_4.Rotation = Vector3.new(0, 0, -90)
			Attachment_4.Axis = Vector3.new(-0, -1, -0)
			Attachment_4.SecondaryAxis = Vector3.new(1, 0, -0)
			local Attachment_7 = Instance.new("Attachment")
			Attachment_7.Name = "TorsoA"
			Attachment_7.Parent = Torso
			Attachment_7.Position = Vector3.new(0.40000, -1, 0)
			Attachment_7.Rotation = Vector3.new(0, 0, -90)
			Attachment_7.Axis = Vector3.new(0, -1, 0)
			Attachment_7.SecondaryAxis = Vector3.new(1, 0, 0)
			local Attachment_2 = Instance.new("Attachment")
			Attachment_2.Name = "TorsoA1"
			Attachment_2.Parent = Torso
			Attachment_2.Position = Vector3.new(-0.4000, -1, 0)
			Attachment_2.Rotation = Vector3.new(0, 0, -90)
			Attachment_2.Axis = Vector3.new(0, -1, 0)
			Attachment_2.SecondaryAxis = Vector3.new(1, 0, 0)
			local Attachment_5 = Instance.new("Attachment")
			Attachment_5.Name = "TorsoA2"
			Attachment_5.Parent = Torso
			Attachment_5.Position = Vector3.new(-1, 0.80000, 0)
			Attachment_5.Rotation = Vector3.new(-0, 0, -0)
			Attachment_5.Axis = Vector3.new(1, -0, 0)
			Attachment_5.SecondaryAxis = Vector3.new(0, 1, -0)
			local Attachment_3 = Instance.new("Attachment")
			Attachment_3.Name = "TorsoA3"
			Attachment_3.Parent = Torso
			Attachment_3.Position = Vector3.new(1, 0.80000, 0)
			Attachment_3.Rotation = Vector3.new(180, 0, 180)
			Attachment_3.Axis = Vector3.new(-1, -0, 0)
			Attachment_3.SecondaryAxis = Vector3.new(-0, 1, -0)
			local Attachment_9 = Instance.new("Attachment")
			Attachment_9.Name = "TorsoA4"
			Attachment_9.Parent = Torso
			Attachment_9.Position = Vector3.new(-0, 1, 0)
			Attachment_9.Rotation = Vector3.new(0, 0, -90)
			Attachment_9.Axis = Vector3.new(0, -1, 0)
			Attachment_9.SecondaryAxis = Vector3.new(1, 0, 0)
			local BallSocketConstraint_17 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_17.Parent = Head_2
			BallSocketConstraint_17.Attachment0 = Attachment_10
			BallSocketConstraint_17.Attachment1 = Attachment_9
			BallSocketConstraint_17.Enabled = true
			local BallSocketConstraint_15 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_15.Parent = Left_Arm
			BallSocketConstraint_15.Attachment0 = Attachment
			BallSocketConstraint_15.Attachment1 = Attachment_5
			BallSocketConstraint_15.Enabled = true
			local BallSocketConstraint_10 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_10.Parent = Right_Arm
			BallSocketConstraint_10.Attachment0 = Attachment_8
			BallSocketConstraint_10.Attachment1 = Attachment_3
			BallSocketConstraint_10.Enabled = true
			local BallSocketConstraint_12 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_12.Parent = Head_2
			BallSocketConstraint_12.Attachment0 = Attachment_10
			BallSocketConstraint_12.Attachment1 = Attachment_9
			BallSocketConstraint_12.Enabled = true
			local BallSocketConstraint_16 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_16.Parent = Torso
			BallSocketConstraint_16.Attachment0 = Attachment_2
			BallSocketConstraint_16.Attachment1 = Attachment_6
			BallSocketConstraint_16.Enabled = true
			local BallSocketConstraint_2 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_2.Parent = Torso
			BallSocketConstraint_2.Attachment0 = Attachment_7
			BallSocketConstraint_2.Attachment1 = Attachment_4
			BallSocketConstraint_2.Enabled = true
		else
			local Head = arg1:FindFirstChild("Head")
			local Humanoid_2 = arg1:FindFirstChild("Humanoid")
			local LeftUpperArm = arg1:FindFirstChild("LeftUpperArm")
			local LeftLowerArm = arg1:FindFirstChild("LeftLowerArm")
			local LeftUpperLeg = arg1:FindFirstChild("LeftUpperLeg")
			local LeftLowerLeg = arg1:FindFirstChild("LeftLowerLeg")
			local LeftFoot = arg1:FindFirstChild("LeftFoot")
			local RightUpperLeg = arg1:FindFirstChild("RightUpperLeg")
			local RightLowerLeg = arg1:FindFirstChild("RightLowerLeg")
			local RightFoot = arg1:FindFirstChild("RightFoot")
			local RightUpperArm = arg1:FindFirstChild("RightUpperArm")
			local RightLowerArm = arg1:FindFirstChild("RightLowerArm")
			local RightHand = arg1:FindFirstChild("RightHand")
			local UpperTorso = arg1:FindFirstChild("UpperTorso")
			local LowerTorso = arg1:FindFirstChild("LowerTorso")
			Humanoid_2.PlatformStand = true
			Humanoid_2.AutoRotate = false
			local BallSocketConstraint_14 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_14.Parent = Head
			BallSocketConstraint_14.Attachment0 = Head.NeckRigAttachment
			BallSocketConstraint_14.Attachment1 = UpperTorso.NeckRigAttachment
			BallSocketConstraint_14.Enabled = true
			BallSocketConstraint_14.LimitsEnabled = true
			BallSocketConstraint_14.TwistLimitsEnabled = true
			BallSocketConstraint_14.UpperAngle = 90
			BallSocketConstraint_14.TwistLowerAngle = -60
			BallSocketConstraint_14.TwistUpperAngle = 60
			local BallSocketConstraint_4 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_4.Parent = LeftUpperArm
			BallSocketConstraint_4.Attachment0 = LeftUpperArm.LeftShoulderRigAttachment
			BallSocketConstraint_4.Attachment1 = UpperTorso.LeftShoulderRigAttachment
			BallSocketConstraint_4.Enabled = true
			BallSocketConstraint_4.LimitsEnabled = false
			BallSocketConstraint_4.TwistLimitsEnabled = false
			BallSocketConstraint_4.UpperAngle = 180
			BallSocketConstraint_4.TwistLowerAngle = -90
			BallSocketConstraint_4.TwistUpperAngle = 0
			local BallSocketConstraint_13 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_13.Parent = LeftUpperArm
			BallSocketConstraint_13.Attachment0 = LeftLowerArm.LeftElbowRigAttachment
			BallSocketConstraint_13.Attachment1 = LeftUpperArm.LeftElbowRigAttachment
			BallSocketConstraint_13.Enabled = true
			BallSocketConstraint_13.LimitsEnabled = true
			BallSocketConstraint_13.TwistLimitsEnabled = true
			BallSocketConstraint_13.UpperAngle = 0
			BallSocketConstraint_13.TwistLowerAngle = -160
			BallSocketConstraint_13.TwistUpperAngle = 0
			local BallSocketConstraint_5 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_5.Parent = LeftUpperArm
			BallSocketConstraint_5.Attachment0 = LeftLowerArm.LeftWristRigAttachment
			BallSocketConstraint_5.Attachment1 = arg1:FindFirstChild("LeftHand").LeftWristRigAttachment
			BallSocketConstraint_5.Enabled = true
			BallSocketConstraint_5.LimitsEnabled = true
			BallSocketConstraint_5.TwistLimitsEnabled = true
			BallSocketConstraint_5.UpperAngle = 25
			BallSocketConstraint_5.TwistLowerAngle = -25
			BallSocketConstraint_5.TwistUpperAngle = 25
			local BallSocketConstraint_11 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_11.Parent = RightUpperArm
			BallSocketConstraint_11.Attachment0 = RightUpperArm.RightShoulderRigAttachment
			BallSocketConstraint_11.Attachment1 = UpperTorso.RightShoulderRigAttachment
			BallSocketConstraint_11.Enabled = true
			BallSocketConstraint_11.LimitsEnabled = false
			BallSocketConstraint_11.TwistLimitsEnabled = false
			BallSocketConstraint_11.UpperAngle = 90
			BallSocketConstraint_11.TwistLowerAngle = 0
			BallSocketConstraint_11.TwistUpperAngle = 0
			local BallSocketConstraint_19 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_19.Parent = RightLowerArm
			BallSocketConstraint_19.Attachment0 = RightLowerArm.RightElbowRigAttachment
			BallSocketConstraint_19.Attachment1 = RightUpperArm.RightElbowRigAttachment
			BallSocketConstraint_19.Enabled = true
			BallSocketConstraint_19.LimitsEnabled = true
			BallSocketConstraint_19.TwistLimitsEnabled = true
			BallSocketConstraint_19.UpperAngle = 0
			BallSocketConstraint_19.TwistLowerAngle = -160
			BallSocketConstraint_19.TwistUpperAngle = 0
			local BallSocketConstraint = Instance.new("BallSocketConstraint")
			BallSocketConstraint.Parent = RightHand
			BallSocketConstraint.Attachment0 = RightLowerArm.RightWristRigAttachment
			BallSocketConstraint.Attachment1 = RightHand.RightWristRigAttachment
			BallSocketConstraint.Enabled = true
			BallSocketConstraint.LimitsEnabled = true
			BallSocketConstraint.TwistLimitsEnabled = true
			BallSocketConstraint.UpperAngle = 25
			BallSocketConstraint.TwistLowerAngle = -25
			BallSocketConstraint.TwistUpperAngle = 25
			local BallSocketConstraint_18 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_18.Parent = UpperTorso
			BallSocketConstraint_18.Attachment0 = UpperTorso.WaistRigAttachment
			BallSocketConstraint_18.Attachment1 = LowerTorso.WaistRigAttachment
			BallSocketConstraint_18.Enabled = true
			BallSocketConstraint_18.LimitsEnabled = true
			BallSocketConstraint_18.TwistLimitsEnabled = true
			BallSocketConstraint_18.UpperAngle = 30
			BallSocketConstraint_18.TwistLowerAngle = -30
			BallSocketConstraint_18.TwistUpperAngle = 30
			local BallSocketConstraint_8 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_8.Parent = RightUpperLeg
			BallSocketConstraint_8.Attachment0 = RightUpperLeg.RightHipRigAttachment
			BallSocketConstraint_8.Attachment1 = LowerTorso.RightHipRigAttachment
			BallSocketConstraint_8.Enabled = true
			BallSocketConstraint_8.LimitsEnabled = true
			BallSocketConstraint_8.TwistLimitsEnabled = true
			BallSocketConstraint_8.UpperAngle = 20
			BallSocketConstraint_8.TwistLowerAngle = -75
			BallSocketConstraint_8.TwistUpperAngle = 75
			local BallSocketConstraint_3 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_3.Parent = RightLowerLeg
			BallSocketConstraint_3.Attachment0 = RightLowerLeg.RightKneeRigAttachment
			BallSocketConstraint_3.Attachment1 = RightUpperLeg.RightKneeRigAttachment
			BallSocketConstraint_3.Enabled = true
			BallSocketConstraint_3.LimitsEnabled = true
			BallSocketConstraint_3.TwistLimitsEnabled = true
			BallSocketConstraint_3.UpperAngle = 0
			BallSocketConstraint_3.TwistLowerAngle = 0
			BallSocketConstraint_3.TwistUpperAngle = 90
			local BallSocketConstraint_6 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_6.Parent = RightFoot
			BallSocketConstraint_6.Attachment0 = RightFoot.RightAnkleRigAttachment
			BallSocketConstraint_6.Attachment1 = RightLowerLeg.RightAnkleRigAttachment
			BallSocketConstraint_6.Enabled = true
			BallSocketConstraint_6.LimitsEnabled = true
			BallSocketConstraint_6.TwistLimitsEnabled = true
			BallSocketConstraint_6.UpperAngle = 25
			BallSocketConstraint_6.TwistLowerAngle = -25
			BallSocketConstraint_6.TwistUpperAngle = 25
			local BallSocketConstraint_9 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_9.Parent = LeftUpperLeg
			BallSocketConstraint_9.Attachment0 = LeftUpperLeg.LeftHipRigAttachment
			BallSocketConstraint_9.Attachment1 = LowerTorso.LeftHipRigAttachment
			BallSocketConstraint_9.Enabled = true
			BallSocketConstraint_9.LimitsEnabled = true
			BallSocketConstraint_9.TwistLimitsEnabled = true
			BallSocketConstraint_9.UpperAngle = 30
			BallSocketConstraint_9.TwistLowerAngle = -90
			BallSocketConstraint_9.TwistUpperAngle = 90
			local BallSocketConstraint_20 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_20.Parent = LeftLowerLeg
			BallSocketConstraint_20.Attachment0 = LeftLowerLeg.LeftKneeRigAttachment
			BallSocketConstraint_20.Attachment1 = LeftUpperLeg.LeftKneeRigAttachment
			BallSocketConstraint_20.Enabled = true
			BallSocketConstraint_20.LimitsEnabled = true
			BallSocketConstraint_20.TwistLimitsEnabled = true
			BallSocketConstraint_20.UpperAngle = 0
			BallSocketConstraint_20.TwistLowerAngle = 0
			BallSocketConstraint_20.TwistUpperAngle = 90
			local BallSocketConstraint_7 = Instance.new("BallSocketConstraint")
			BallSocketConstraint_7.Parent = LeftFoot
			BallSocketConstraint_7.Attachment0 = LeftFoot.LeftAnkleRigAttachment
			BallSocketConstraint_7.Attachment1 = LeftLowerLeg.LeftAnkleRigAttachment
			BallSocketConstraint_7.Enabled = true
			BallSocketConstraint_7.LimitsEnabled = true
			BallSocketConstraint_7.TwistLimitsEnabled = true
			BallSocketConstraint_7.UpperAngle = 25
			BallSocketConstraint_7.TwistLowerAngle = -25
			BallSocketConstraint_7.TwistUpperAngle = 25
		end
		for _, v in pairs(arg1:GetDescendants()) do
			if not v:IsA("Accessory") and not v:IsA("Model") and v:IsA("Motor6D") then
				v:Destroy()
			end
		end
		if arg1:FindFirstChild("HumanoidRootPart") ~= nil then
			arg1.HumanoidRootPart:Destroy()
		end
	end
end